    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Connections.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class DataKriteria extends javax.swing.JFrame {

    private Connection conn = new connect().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form Kriteria
     */
    public DataKriteria() {
        initComponents();
        datatable();
        autoKodeKriteria();
        this.setLocationRelativeTo(null);
    }

    private void clear() {
        k_kode.setText("");
        k_nama.setText("");
        k_nilai.setText("");
        k_tipe.setSelectedIndex(0);
    }

    private void active() {
        k_kode.setEnabled(true);
        k_nama.setEnabled(true);
        k_nilai.setEnabled(true);
        k_tipe.setEnabled(true);
        k_kode.requestFocus();
    }

    protected void datatable() {
        Object[] kolom = {"Kode", "Nama Kriteria", "Tipe", "Bobot"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tablekriteria.setModel(model);

        String sql = "SELECT kode_kriteria, nama_kriteria, tipe_kriteria, bobot_kriteria FROM kriteria";
        try {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_kriteria"),
                    rs.getString("nama_kriteria"),
                    rs.getString("tipe_kriteria"),
                    rs.getDouble("bobot_kriteria")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }

    private void autoKodeKriteria() {
        try {
            String sql = "SELECT MAX(kode_kriteria) FROM kriteria";
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString(1);
                k_kode.setEnabled(false);
                if (kode == null) {
                    k_kode.setText("C001");
                    
                } else {
                    int no = Integer.parseInt(kode.substring(1)) + 1;
                    String kodeBaru = String.format("C%03d", no);
                    k_kode.setText(kodeBaru);
                
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal generate kode siswa: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        k_kode = new javax.swing.JTextField();
        k_nama = new javax.swing.JTextField();
        k_nilai = new javax.swing.JTextField();
        k_simpan = new javax.swing.JButton();
        k_ubah = new javax.swing.JButton();
        k_hapus = new javax.swing.JButton();
        k_kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablekriteria = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        k_tipe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Kriteria");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Kriteria");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Kriteria");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nilai / Bobot");

        k_kode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        k_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_kodeActionPerformed(evt);
            }
        });

        k_nama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        k_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_namaActionPerformed(evt);
            }
        });

        k_nilai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        k_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_nilaiActionPerformed(evt);
            }
        });

        k_simpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        k_simpan.setText("Simpan");
        k_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_simpanActionPerformed(evt);
            }
        });

        k_ubah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        k_ubah.setText("Ubah");
        k_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_ubahActionPerformed(evt);
            }
        });

        k_hapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        k_hapus.setText("Hapus");
        k_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_hapusActionPerformed(evt);
            }
        });

        k_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        k_kembali.setText("Kembali");
        k_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_kembaliActionPerformed(evt);
            }
        });

        tablekriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablekriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablekriteriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablekriteria);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipe Kriteria");

        k_tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benefit", "Cost" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(87, 87, 87)
                                .addComponent(k_nama))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(k_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k_kembali)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(93, 93, 93)
                                .addComponent(k_kode))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(96, 96, 96)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(k_nilai)
                                    .addComponent(k_tipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(211, 211, 211))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(k_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(k_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(k_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(k_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(k_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(k_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(k_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1070, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void k_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_kodeActionPerformed

    private void k_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_namaActionPerformed

    private void k_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_nilaiActionPerformed

    private void k_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_kembaliActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        k_simpan.setVisible(true);
        dispose();
    }//GEN-LAST:event_k_kembaliActionPerformed

    private void tablekriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablekriteriaMouseClicked
        int baris = tablekriteria.getSelectedRow();
        k_kode.setText(tablekriteria.getValueAt(baris, 0).toString());
        k_nama.setText(tablekriteria.getValueAt(baris, 1).toString());
        k_tipe.setSelectedItem(tablekriteria.getValueAt(baris, 2).toString());
        k_nilai.setText(tablekriteria.getValueAt(baris, 3).toString());
        
        k_simpan.setVisible(false);
    }//GEN-LAST:event_tablekriteriaMouseClicked

    private void k_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_simpanActionPerformed
        String sql = "INSERT INTO kriteria (kode_kriteria, nama_kriteria, tipe_kriteria, bobot_kriteria) VALUES (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, k_kode.getText());
            stat.setString(2, k_nama.getText());
            stat.setString(3, k_tipe.getSelectedItem().toString()); // JComboBox
            stat.setDouble(4, Double.parseDouble(k_nilai.getText()));

            stat.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            clear();
            datatable();
            autoKodeKriteria();
            k_kode.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_k_simpanActionPerformed

    private void k_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_ubahActionPerformed
        String sql = "UPDATE kriteria SET nama_kriteria=?, tipe_kriteria=?, bobot_kriteria=? WHERE kode_kriteria=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, k_nama.getText());
            stat.setString(2, k_tipe.getSelectedItem().toString());
            stat.setDouble(3, Double.parseDouble(k_nilai.getText()));
            stat.setString(4, k_kode.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");

            clear();
            datatable();
            k_simpan.setVisible(true);
            autoKodeKriteria();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data gagal diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_k_ubahActionPerformed

    private void k_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_hapusActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM kriteria WHERE kode_kriteria=?";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, k_kode.getText());
                stat.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

                clear();
                datatable();
                k_simpan.setVisible(true);
                autoKodeKriteria();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_k_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton k_hapus;
    private javax.swing.JButton k_kembali;
    private javax.swing.JTextField k_kode;
    private javax.swing.JTextField k_nama;
    private javax.swing.JTextField k_nilai;
    private javax.swing.JButton k_simpan;
    private javax.swing.JComboBox<String> k_tipe;
    private javax.swing.JButton k_ubah;
    private javax.swing.JTable tablekriteria;
    // End of variables declaration//GEN-END:variables
}
