/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Connections.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class DataAlternatif extends javax.swing.JFrame {

    private Connection conn = new connect().connect();
    private DefaultTableModel tabmode;

    public DataAlternatif() {
        initComponents();
        datatable();
        autoKodeAlternatif();
        ds_kode.setEditable(false);
        this.setLocationRelativeTo(null);
        ds_cari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                cariData(ds_cari.getText());
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                cariData(ds_cari.getText());
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                cariData(ds_cari.getText());
            }
        });
    }

    private void clear() {
        ds_kode.setText("");
        ds_nama.setText("");
    }

    private void active() {
        ds_kode.setText("");
        ds_nama.setEnabled(true);
    }

    protected void datatable() {
        Object[] clcis = {"Kode Alternatif", "Nama Alternatif"};
        tabmode = new DefaultTableModel(null, clcis);
        tablealternatif.setModel(tabmode);
        String sql = "SELECT kode_alternatif, nama_alternatif FROM alternatif";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("kode_alternatif");
                String b = hasil.getString("nama_alternatif");
                tabmode.addRow(new Object[]{a, b});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load tabel: " + e.getMessage());
        }
    }

    private void autoKodeAlternatif() {
        try {
            String sql = "SELECT MAX(kode_alternatif) FROM alternatif";
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString(1);
                ds_kode.setEnabled(false);
                if (kode == null) {
                    ds_kode.setText("A001");
                } else {
                    int no = Integer.parseInt(kode.substring(1)) + 1;
                    ds_kode.setText(String.format("A%03d", no));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal generate kode alternatif: " + e.getMessage());
        }
    }

    private void cariData(String keyword) {
        Object[] clcis = {"Kode Alternatif", "Nama Alternatif"};
        tabmode = new DefaultTableModel(null, clcis);
        tablealternatif.setModel(tabmode);
        String sql = "SELECT kode_alternatif, nama_alternatif FROM alternatif WHERE nama_alternatif LIKE ?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "%" + keyword + "%");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tabmode.addRow(new Object[]{rs.getString("kode_alternatif"), rs.getString("nama_alternatif")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Pencarian gagal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ds_nama = new javax.swing.JTextField();
        ds_kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealternatif = new javax.swing.JTable();
        ds_cari = new javax.swing.JTextField();
        ds_simpan = new javax.swing.JButton();
        ds_ubah = new javax.swing.JButton();
        ds_hapus = new javax.swing.JButton();
        ds_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Alternatif");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(600, 600, 600))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 475));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Alternatif");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Alternatif");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cari Nama");

        ds_nama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        ds_kode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ds_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_kodeActionPerformed(evt);
            }
        });

        tablealternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablealternatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablealternatifMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablealternatif);

        ds_cari.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ds_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_cariActionPerformed(evt);
            }
        });

        ds_simpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ds_simpan.setText("Simpan");
        ds_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_simpanActionPerformed(evt);
            }
        });

        ds_ubah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ds_ubah.setText("Ubah");
        ds_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_ubahActionPerformed(evt);
            }
        });

        ds_hapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ds_hapus.setText("Hapus");
        ds_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_hapusActionPerformed(evt);
            }
        });

        ds_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ds_kembali.setText("Kembali");
        ds_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ds_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ds_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ds_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ds_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ds_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ds_kode, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                        .addComponent(ds_nama)))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ds_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(ds_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ds_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ds_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1050, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ds_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_kembaliActionPerformed
        new Menu().setVisible(true);
        ds_simpan.setVisible(true);
        dispose();
    }//GEN-LAST:event_ds_kembaliActionPerformed

    private void ds_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_hapusActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM alternatif WHERE kode_alternatif=?";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, ds_kode.getText());
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

                datatable();
                clear();
                ds_simpan.setVisible(true);
                autoKodeAlternatif();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_ds_hapusActionPerformed

    private void ds_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_ubahActionPerformed
        String sql = "UPDATE alternatif SET nama_alternatif=? WHERE kode_alternatif=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ds_nama.getText());
            ps.setString(2, ds_kode.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");

            datatable();
            clear();
            ds_simpan.setVisible(true);
            autoKodeAlternatif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal ubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_ds_ubahActionPerformed

    private void ds_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_simpanActionPerformed
        String sql = "INSERT INTO alternatif (kode_alternatif, nama_alternatif) VALUES (?, ?)";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ds_kode.getText());
            ps.setString(2, ds_nama.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            datatable();
            clear();
            autoKodeAlternatif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_ds_simpanActionPerformed

    private void ds_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ds_cariActionPerformed

    private void tablealternatifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablealternatifMouseClicked
        int bar = tablealternatif.getSelectedRow();
        ds_kode.setText(tabmode.getValueAt(bar, 0).toString());
        ds_nama.setText(tabmode.getValueAt(bar, 1).toString());

        ds_simpan.setVisible(false);
    }//GEN-LAST:event_tablealternatifMouseClicked

    private void ds_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ds_kodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAlternatif.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAlternatif.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAlternatif.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAlternatif.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataAlternatif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ds_cari;
    private javax.swing.JButton ds_hapus;
    private javax.swing.JButton ds_kembali;
    private javax.swing.JTextField ds_kode;
    private javax.swing.JTextField ds_nama;
    private javax.swing.JButton ds_simpan;
    private javax.swing.JButton ds_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablealternatif;
    // End of variables declaration//GEN-END:variables
}
