/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Data = new javax.swing.JMenu();
        datasiswa = new javax.swing.JMenuItem();
        datakriteria = new javax.swing.JMenuItem();
        datanilai = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        penilaian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        Data.setText("Data");
        Data.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        datasiswa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        datasiswa.setText("Data Alternatif");
        datasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasiswaActionPerformed(evt);
            }
        });
        Data.add(datasiswa);

        datakriteria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        datakriteria.setText("Data Kriteria");
        datakriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakriteriaActionPerformed(evt);
            }
        });
        Data.add(datakriteria);

        datanilai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        datanilai.setText("Data Nilai");
        datanilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanilaiActionPerformed(evt);
            }
        });
        Data.add(datanilai);

        jMenuBar1.add(Data);

        jMenu2.setText("Penilaian");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        penilaian.setText("Proses Perhitungan");
        penilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penilaianActionPerformed(evt);
            }
        });
        jMenu2.add(penilaian);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pengaturan");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem4.setText("Keluar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasiswaActionPerformed
        new DataAlternatif().setVisible(true);
        dispose();
    }//GEN-LAST:event_datasiswaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void datakriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakriteriaActionPerformed
        // TODO add your handling code here:
        new DataKriteria().setVisible(true);
        dispose();
    }//GEN-LAST:event_datakriteriaActionPerformed

    private void datanilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanilaiActionPerformed
        // TODO add your handling code here:
        new Nilai().setVisible(true);
        dispose();
    }//GEN-LAST:event_datanilaiActionPerformed

    private void penilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penilaianActionPerformed
        // TODO add your handling code here:
        new Proses_ARAS().setVisible(true);
        dispose();
    }//GEN-LAST:event_penilaianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Data;
    private javax.swing.JMenuItem datakriteria;
    private javax.swing.JMenuItem datanilai;
    private javax.swing.JMenuItem datasiswa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem penilaian;
    // End of variables declaration//GEN-END:variables
}
